#  This file is automatically generated; change it on your own risk!

#--begin constants--

single_input = 731000
file_input = 731001
eval_input = 731002
decorator = 731003
decorators = 731004
decorated = 731005
funcdef = 731006
parameters = 731007
varargslist = 731008
fpdef = 731009
fplist = 731010
stmt = 731011
simple_stmt = 731012
small_stmt = 731013
expr_stmt = 731014
augassign = 731015
print_stmt = 731016
del_stmt = 731017
pass_stmt = 731018
flow_stmt = 731019
break_stmt = 731020
continue_stmt = 731021
return_stmt = 731022
yield_stmt = 731023
raise_stmt = 731024
import_stmt = 731025
import_name = 731026
import_from = 731027
import_as_name = 731028
dotted_as_name = 731029
import_as_names = 731030
dotted_as_names = 731031
dotted_name = 731032
global_stmt = 731033
exec_stmt = 731034
assert_stmt = 731035
compound_stmt = 731036
if_stmt = 731037
while_stmt = 731038
for_stmt = 731039
try_stmt = 731040
with_stmt = 731041
with_item = 731042
except_clause = 731043
suite = 731044
testlist_safe = 731045
old_test = 731046
old_lambdef = 731047
test = 731048
or_test = 731049
and_test = 731050
not_test = 731051
comparison = 731052
comp_op = 731053
expr = 731054
xor_expr = 731055
and_expr = 731056
shift_expr = 731057
arith_expr = 731058
term = 731059
factor = 731060
power = 731061
atom = 731062
listmaker = 731063
testlist_comp = 731064
lambdef = 731065
trailer = 731066
subscriptlist = 731067
subscript = 731068
sliceop = 731069
exprlist = 731070
testlist = 731071
dictmaker = 731072
dictorsetmaker = 731073
classdef = 731074
arglist = 731075
argument = 731076
list_iter = 731077
list_for = 731078
list_if = 731079
comp_iter = 731080
comp_for = 731081
comp_if = 731082
testlist1 = 731083
encoding_decl = 731084
yield_expr = 731085
p4d_compound_stmt = 731086
p4d_element = 731087
p4d_attribute = 731088
p4d_attribute_list = 731089
p4d_suite = 731090
p4d_simple_stmt = 731091
p4d_stmt = 731092
p4d_expr = 731093
p4d_accessor = 731094
p4d_attr_access = 731095
p4d_name = 731096
SPECNUM = 731097

#--end constants--

tok_name = sym_name = {}
for _name, _value in globals().items():
    if type(_value) is type(0):
        sym_name[_value] = _name

del _name
del _value
