#  This file is automatically generated; change it on your own risk!

#--begin constants--

single_input = 731000
file_input = 731001
eval_input = 731002
decorator = 731003
decorators = 731004
funcdef = 731005
parameters = 731006
varargslist = 731007
fpdef = 731008
fplist = 731009
stmt = 731010
simple_stmt = 731011
small_stmt = 731012
expr_stmt = 731013
augassign = 731014
print_stmt = 731015
del_stmt = 731016
pass_stmt = 731017
flow_stmt = 731018
break_stmt = 731019
continue_stmt = 731020
return_stmt = 731021
yield_stmt = 731022
raise_stmt = 731023
import_stmt = 731024
import_name = 731025
import_from = 731026
import_as_name = 731027
dotted_as_name = 731028
import_as_names = 731029
dotted_as_names = 731030
dotted_name = 731031
global_stmt = 731032
exec_stmt = 731033
assert_stmt = 731034
compound_stmt = 731035
if_stmt = 731036
while_stmt = 731037
for_stmt = 731038
try_stmt = 731039
with_stmt = 731040
with_var = 731041
except_clause = 731042
suite = 731043
testlist_safe = 731044
old_test = 731045
old_lambdef = 731046
test = 731047
or_test = 731048
and_test = 731049
not_test = 731050
comparison = 731051
comp_op = 731052
expr = 731053
xor_expr = 731054
and_expr = 731055
shift_expr = 731056
arith_expr = 731057
term = 731058
factor = 731059
power = 731060
atom = 731061
listmaker = 731062
testlist_gexp = 731063
lambdef = 731064
trailer = 731065
subscriptlist = 731066
subscript = 731067
sliceop = 731068
exprlist = 731069
testlist = 731070
dictmaker = 731071
classdef = 731072
arglist = 731073
argument = 731074
list_iter = 731075
list_for = 731076
list_if = 731077
gen_iter = 731078
gen_for = 731079
gen_if = 731080
testlist1 = 731081
encoding_decl = 731082
yield_expr = 731083
p4d_compound_stmt = 731084
p4d_element = 731085
p4d_attribute = 731086
p4d_attribute_list = 731087
p4d_suite = 731088
p4d_simple_stmt = 731089
p4d_stmt = 731090
p4d_expr = 731091
p4d_accessor = 731092
p4d_attr_access = 731093
p4d_name = 731094
SPECNUM = 731095

#--end constants--

tok_name = sym_name = {}
for _name, _value in globals().items():
    if type(_value) is type(0):
        sym_name[_value] = _name

del _name
del _value
