#  This file is automatically generated; change it on your own risk!

#--begin constants--

ENDMARKER = 981000
NAME = 981001
NUMBER = 981002
STRING = 981003
NEWLINE = 981004
LPAR = 981005
RPAR = 981006
LSQB = 981007
RSQB = 981008
COLON = 981009
SEMI = 981010
PLUS = 981011
STAR = 981012
VBAR = 981013
COMMENT = 981014
token_input = 981015
unit = 981016
LBRA = 981017
RBRA = 981018
COMMA = 981019
LINE_COMMENT = 981020
INTRON = 981021
WHITE = 981022
Single = 981023
Double = 981024

#--end constants--

tok_name = sym_name = {}
for _name, _value in globals().items():
    if type(_value) is type(0):
        sym_name[_value] = _name

del _name
del _value

token_map = {'""(A_BACKSLASHANY|ANY)*""': 981024,
 '"(A_BACKSLASHANY|ANY)*"': 981025,
 '#': 981021,
 '(': 981006,
 '(NAME|INTRON|LPAR|RPAR|LSQB|RSQB|COLON|PLUS|STAR|VBAR|STRING|LBRA|RBRA|COMMA|SEMI)': 981017,
 ')': 981007,
 '*': 981013,
 '+': 981012,
 ',': 981020,
 ':': 981010,
 ';': 981011,
 'A_CHAR(A_CHAR|A_DIGIT)*': 981002,
 'A_DIGIT+': 981003,
 'A_LINE_END': 981005,
 'A_WHITE+': 981023,
 'LINE_COMMENTANY*A_LINE_END': 981015,
 'NEWLINE|WHITE|COMMENT': 981022,
 'Single|Double': 981004,
 'T_ENDMARKER': 981001,
 '[': 981008,
 ']': 981009,
 'unit*ENDMARKER': 981016,
 '{': 981018,
 '|': 981014,
 '}': 981019}
