def build_cstbuilder(cstbuilder):
    and_expr         = cstbuilder.builder(831056, 'and_expr', "and_expr: shift_expr ('&' shift_expr)*")
    and_test         = cstbuilder.builder(831050, 'and_test', "and_test: not_test ('and' not_test)*")
    arglist          = cstbuilder.builder(831075, 'arglist', "arglist: ( argument ',')* ( argument [','] | '*' test (',' argument)* [',' '**' test] | '**' test)")
    argument         = cstbuilder.builder(831076, 'argument', "argument: test [comp_for] | test '=' test")
    arith_expr       = cstbuilder.builder(831058, 'arith_expr', "arith_expr: term (('+' | '-') term)*")
    as_name          = cstbuilder.builder(831086, 'as_name', "as_name: 'as' NAME")
    assert_stmt      = cstbuilder.builder(831035, 'assert_stmt', "assert_stmt: 'assert' test [',' test]")
    atom             = cstbuilder.builder(831062, 'atom', "atom: ('(' [yield_expr | testlist_comp] ')' | '[' [listmaker] ']' | '{' [dictorsetmaker] '}' | '`' testlist1 '`' | NAME | NUMBER | STRING+) | IPv4Address")
    augassign        = cstbuilder.builder(831015, 'augassign', "augassign: ('+=' | '-=' | '*=' | '/=' | '%=' | '&=' | '|=' | '^=' | '<<=' | '>>=' | '**=' | '//=')")
    break_stmt       = cstbuilder.builder(831020, 'break_stmt', "break_stmt: 'break'")
    case_stmt        = cstbuilder.builder(831089, 'case_stmt', "case_stmt: 'case' expr ':' suite ('case' expr ':' suite)*")
    classdef         = cstbuilder.builder(831074, 'classdef', "classdef: 'class' NAME ['(' [testlist] ')'] ':' suite")
    comp_for         = cstbuilder.builder(831081, 'comp_for', "comp_for: 'for' exprlist 'in' or_test [comp_iter] | 'for' exprlist 'with' expr '=' expr")
    comp_if          = cstbuilder.builder(831082, 'comp_if', "comp_if: 'if' old_test [comp_iter]")
    comp_iter        = cstbuilder.builder(831080, 'comp_iter', "comp_iter: comp_for | comp_if")
    comp_op          = cstbuilder.builder(831053, 'comp_op', "comp_op: '<' | '>' | '==' | '>=' | '<=' | '<>' | '!=' | 'in' | 'not' 'in' | 'is' | 'is' 'not'")
    comparison       = cstbuilder.builder(831052, 'comparison', "comparison: expr ( comp_op expr)*")
    compound_stmt    = cstbuilder.builder(831036, 'compound_stmt', "compound_stmt: if_stmt | while_stmt | for_stmt | try_stmt | with_stmt | funcdef | classdef | decorated | repeat_stmt | switch_stmt | thunk_stmt")
    continue_stmt    = cstbuilder.builder(831021, 'continue_stmt', "continue_stmt: 'continue'")
    decorated        = cstbuilder.builder(831005, 'decorated', "decorated: decorators ( classdef | funcdef)")
    decorator        = cstbuilder.builder(831003, 'decorator', "decorator: '@' dotted_name ['(' [arglist] ')'] NEWLINE")
    decorators       = cstbuilder.builder(831004, 'decorators', "decorators: decorator+")
    del_stmt         = cstbuilder.builder(831017, 'del_stmt', "del_stmt: 'del' exprlist")
    dictmaker        = cstbuilder.builder(831072, 'dictmaker', "dictmaker: test ':' test (',' test ':' test)* [',']")
    dictorsetmaker   = cstbuilder.builder(831073, 'dictorsetmaker', "dictorsetmaker: (( test ':' test ( comp_for | (',' test ':' test)* [','])) | ( test ( comp_for | (',' test)* [','])))")
    dotted_as_name   = cstbuilder.builder(831029, 'dotted_as_name', "dotted_as_name: dotted_name ['as' NAME]")
    dotted_as_names  = cstbuilder.builder(831031, 'dotted_as_names', "dotted_as_names: dotted_as_name (',' dotted_as_name)*")
    dotted_name      = cstbuilder.builder(831032, 'dotted_name', "dotted_name: NAME ('.' NAME)*")
    encoding_decl    = cstbuilder.builder(831084, 'encoding_decl', "encoding_decl: NAME")
    eval_input       = cstbuilder.builder(831002, 'eval_input', "eval_input: testlist NEWLINE* ENDMARKER")
    except_clause    = cstbuilder.builder(831043, 'except_clause', "except_clause: 'except' [test [('as' | ',') test]]")
    exec_stmt        = cstbuilder.builder(831034, 'exec_stmt', "exec_stmt: 'exec' expr ['in' test [',' test]]")
    expr             = cstbuilder.builder(831054, 'expr', "expr: xor_expr ('|' xor_expr)*")
    expr_stmt        = cstbuilder.builder(831014, 'expr_stmt', "expr_stmt: testlist ( augassign ( yield_expr | testlist) | ('=' ( yield_expr | testlist))*)")
    exprlist         = cstbuilder.builder(831070, 'exprlist', "exprlist: expr (',' expr)* [',']")
    factor           = cstbuilder.builder(831060, 'factor', "factor: ('+' | '-' | '~') factor | power")
    file_input       = cstbuilder.builder(831001, 'file_input', "file_input: ( NEWLINE | stmt)* ENDMARKER")
    flow_stmt        = cstbuilder.builder(831019, 'flow_stmt', "flow_stmt: break_stmt | continue_stmt | return_stmt | raise_stmt | yield_stmt")
    for_stmt         = cstbuilder.builder(831039, 'for_stmt', "for_stmt: 'for' exprlist 'in' testlist ':' suite ['else' ':' suite]")
    fpdef            = cstbuilder.builder(831009, 'fpdef', "fpdef: NAME | '(' fplist ')'")
    fplist           = cstbuilder.builder(831010, 'fplist', "fplist: fpdef (',' fpdef)* [',']")
    funcdef          = cstbuilder.builder(831006, 'funcdef', "funcdef: 'def' NAME parameters ':' suite")
    global_stmt      = cstbuilder.builder(831033, 'global_stmt', "global_stmt: 'global' NAME (',' NAME)*")
    if_stmt          = cstbuilder.builder(831037, 'if_stmt', "if_stmt: 'if' test [as_name] ':' suite ('elif' test [as_name] ':' suite)* ['else' ':' suite]")
    import_as_name   = cstbuilder.builder(831028, 'import_as_name', "import_as_name: NAME ['as' NAME]")
    import_as_names  = cstbuilder.builder(831030, 'import_as_names', "import_as_names: import_as_name (',' import_as_name)* [',']")
    import_from      = cstbuilder.builder(831027, 'import_from', "import_from: ('from' ('.'* dotted_name | '.'+) 'import' ('*' | '(' import_as_names ')' | import_as_names))")
    import_name      = cstbuilder.builder(831026, 'import_name', "import_name: 'import' dotted_as_names")
    import_stmt      = cstbuilder.builder(831025, 'import_stmt', "import_stmt: import_name | import_from")
    lambdef          = cstbuilder.builder(831065, 'lambdef', "lambdef: 'lambda' [varargslist] ':' test")
    list_for         = cstbuilder.builder(831078, 'list_for', "list_for: 'for' exprlist 'in' testlist_safe [list_iter]")
    list_if          = cstbuilder.builder(831079, 'list_if', "list_if: 'if' old_test [list_iter]")
    list_iter        = cstbuilder.builder(831077, 'list_iter', "list_iter: list_for | list_if")
    listmaker        = cstbuilder.builder(831063, 'listmaker', "listmaker: test ( list_for | (',' test)* [','])")
    not_test         = cstbuilder.builder(831051, 'not_test', "not_test: 'not' not_test | comparison")
    old_lambdef      = cstbuilder.builder(831047, 'old_lambdef', "old_lambdef: 'lambda' [varargslist] ':' old_test")
    old_test         = cstbuilder.builder(831046, 'old_test', "old_test: or_test | old_lambdef")
    or_test          = cstbuilder.builder(831049, 'or_test', "or_test: and_test ('or' and_test)*")
    parameters       = cstbuilder.builder(831007, 'parameters', "parameters: '(' [varargslist] ')'")
    pass_stmt        = cstbuilder.builder(831018, 'pass_stmt', "pass_stmt: 'pass'")
    power            = cstbuilder.builder(831061, 'power', "power: atom trailer* ['**' factor]")
    print_stmt       = cstbuilder.builder(831016, 'print_stmt', "print_stmt: 'print' ([test (',' test)* [',']] | '>>' test [(',' test)+ [',']])")
    raise_stmt       = cstbuilder.builder(831024, 'raise_stmt', "raise_stmt: 'raise' [test [',' test [',' test]]]")
    repeat_stmt      = cstbuilder.builder(831087, 'repeat_stmt', "repeat_stmt: 'repeat' ':' suite 'until' ':' ( NEWLINE INDENT test NEWLINE DEDENT | test NEWLINE)")
    return_stmt      = cstbuilder.builder(831022, 'return_stmt', "return_stmt: 'return' [testlist]")
    shift_expr       = cstbuilder.builder(831057, 'shift_expr', "shift_expr: arith_expr (('<<' | '>>') arith_expr)*")
    simple_stmt      = cstbuilder.builder(831012, 'simple_stmt', "simple_stmt: small_stmt (';' small_stmt)* [';'] NEWLINE")
    single_input     = cstbuilder.builder(831000, 'single_input', "single_input: NEWLINE | simple_stmt | compound_stmt NEWLINE")
    sliceop          = cstbuilder.builder(831069, 'sliceop', "sliceop: ':' [test]")
    small_stmt       = cstbuilder.builder(831013, 'small_stmt', "small_stmt: ( expr_stmt | print_stmt | del_stmt | pass_stmt | flow_stmt | import_stmt | global_stmt | exec_stmt | assert_stmt)")
    stmt             = cstbuilder.builder(831011, 'stmt', "stmt: simple_stmt | compound_stmt")
    subscript        = cstbuilder.builder(831068, 'subscript', "subscript: '.' '.' '.' | test | [test] ':' [test] [sliceop]")
    subscriptlist    = cstbuilder.builder(831067, 'subscriptlist', "subscriptlist: subscript (',' subscript)* [',']")
    suite            = cstbuilder.builder(831044, 'suite', "suite: simple_stmt | NEWLINE INDENT stmt+ DEDENT")
    switch_stmt      = cstbuilder.builder(831088, 'switch_stmt', "switch_stmt: 'switch' expr ':' NEWLINE INDENT case_stmt DEDENT ['else' ':' suite]")
    term             = cstbuilder.builder(831059, 'term', "term: factor (('*' | '/' | '%' | '//') factor)*")
    test             = cstbuilder.builder(831048, 'test', "test: or_test ['if' or_test 'else' test] | lambdef")
    testlist         = cstbuilder.builder(831071, 'testlist', "testlist: test (',' test)* [',']")
    testlist1        = cstbuilder.builder(831083, 'testlist1', "testlist1: test (',' test)*")
    testlist_comp    = cstbuilder.builder(831064, 'testlist_comp', "testlist_comp: test ( comp_for | (',' test)* [','])")
    testlist_safe    = cstbuilder.builder(831045, 'testlist_safe', "testlist_safe: old_test [(',' old_test)+ [',']]")
    thunk_stmt       = cstbuilder.builder(831090, 'thunk_stmt', "thunk_stmt: small_stmt ':' suite")
    trailer          = cstbuilder.builder(831066, 'trailer', "trailer: '(' [arglist] ')' | '[' subscriptlist ']' | '.' NAME")
    try_stmt         = cstbuilder.builder(831040, 'try_stmt', "try_stmt: ('try' ':' suite (( except_clause ':' suite)+ ['else' ':' suite] ['finally' ':' suite] | 'finally' ':' suite))")
    varargslist      = cstbuilder.builder(831008, 'varargslist', "varargslist: (( fpdef ['=' test] ',')* ('*' NAME [',' '**' NAME] | '**' NAME) | fpdef ['=' test] (',' fpdef ['=' test])* [','])")
    while_stmt       = cstbuilder.builder(831038, 'while_stmt', "while_stmt: 'while' test ':' suite ['else' ':' suite]")
    with_item        = cstbuilder.builder(831042, 'with_item', "with_item: test ['as' expr]")
    with_stmt        = cstbuilder.builder(831041, 'with_stmt', "with_stmt: 'with' with_item (',' with_item)* ':' suite")
    xor_expr         = cstbuilder.builder(831055, 'xor_expr', "xor_expr: and_expr ('^' and_expr)*")
    yield_expr       = cstbuilder.builder(831085, 'yield_expr', "yield_expr: 'yield' [testlist]")
    yield_stmt       = cstbuilder.builder(831023, 'yield_stmt', "yield_stmt: yield_expr")
    return locals()

