#  This file is automatically generated; change it on your own risk!

#--begin constants--

eval_input = 111000
file_input = 111001
rule = 111002
rhs = 111003
alt = 111004
variable = 111005
item = 111006
atom = 111007
repeated = 111008

#--end constants--

tok_name = sym_name = {}
for _name, _value in globals().items():
    if type(_value) is type(0):
        sym_name[_value] = _name

del _name
del _value
