#  This file is automatically generated; change it on your own risk!

#--begin constants--

ENDMARKER = 110000
NAME = 110001
NUMBER = 110002
STRING = 110003
NEWLINE = 110004
INDENT = 110005
DEDENT = 110006
LPAR = 110007
RPAR = 110008
LSQB = 110009
RSQB = 110010
COLON = 110011
PLUS = 110012
STAR = 110013
VBAR = 110014
COMMENT = 110015
token_input = 110016
unit = 110017
LBRA = 110018
RBRA = 110019
COMMA = 110020
LINE_COMMENT = 110021
WHITE = 110022
Single = 110023
Double = 110024

#--end constants--

tok_name = sym_name = {}
for _name, _value in globals().items():
    if type(_value) is type(0):
        sym_name[_value] = _name

del _name
del _value

token_map = {'""(A_BACKSLASHANY|ANY)*""': 110023,
 '"(A_BACKSLASHANY|ANY)*"': 110024,
 '#': 110021,
 '(': 110007,
 ')': 110008,
 '*': 110013,
 '+': 110012,
 ',': 110020,
 ':': 110011,
 'A_CHAR(A_CHAR|A_DIGIT)*': 110001,
 'A_DIGIT+': 110002,
 'A_LINE_END': 110004,
 'A_WHITE+': 110022,
 'LINE_COMMENTANY*A_LINE_END': 110015,
 'NAME|NEWLINE|LPAR|RPAR|LSQB|RSQB|COLON|PLUS|STAR|WHITE|VBAR|STRING|COMMENT|LBRA|RBRA|COMMA': 110017,
 'Single|Double': 110003,
 'T_DEDENT': 110006,
 'T_ENDMARKER': 110000,
 'T_INDENT': 110005,
 '[': 110009,
 ']': 110010,
 'unit*ENDMARKER': 110016,
 '{': 110018,
 '|': 110014,
 '}': 110019}


symbol_map = {110007: '(',
 110008: ')',
 110009: '[',
 110010: ']',
 110011: ':',
 110012: '+',
 110013: '*',
 110014: '|',
 110018: '{',
 110019: '}',
 110020: ',',
 110021: '#'}

