#  This file is automatically generated; change it on your own risk!

#--begin constants--

eval_input = 761000
file_input = 761001
rule = 761002
rhs = 761003
alt = 761004
item = 761005
atom = 761006

#--end constants--

tok_name = sym_name = {}
for _name, _value in globals().items():
    if type(_value) is type(0):
        sym_name[_value] = _name

del _name
del _value
