#  This file is automatically generated; change it on your own risk!

#--begin constants--

single_input = 1000
file_input = 1001
eval_input = 1002
decorator = 1003
decorators = 1004
funcdef = 1005
parameters = 1006
varargslist = 1007
fpdef = 1008
fplist = 1009
stmt = 1010
simple_stmt = 1011
small_stmt = 1012
expr_stmt = 1013
augassign = 1014
print_stmt = 1015
del_stmt = 1016
pass_stmt = 1017
flow_stmt = 1018
break_stmt = 1019
continue_stmt = 1020
return_stmt = 1021
yield_stmt = 1022
raise_stmt = 1023
import_stmt = 1024
import_name = 1025
import_from = 1026
import_as_name = 1027
dotted_as_name = 1028
import_as_names = 1029
dotted_as_names = 1030
dotted_name = 1031
global_stmt = 1032
exec_stmt = 1033
assert_stmt = 1034
compound_stmt = 1035
if_stmt = 1036
while_stmt = 1037
for_stmt = 1038
try_stmt = 1039
with_stmt = 1040
with_var = 1041
except_clause = 1042
suite = 1043
testlist_safe = 1044
old_test = 1045
old_lambdef = 1046
test = 1047
or_test = 1048
and_test = 1049
not_test = 1050
comparison = 1051
comp_op = 1052
expr = 1053
xor_expr = 1054
and_expr = 1055
shift_expr = 1056
arith_expr = 1057
term = 1058
factor = 1059
power = 1060
atom = 1061
listmaker = 1062
testlist_gexp = 1063
lambdef = 1064
trailer = 1065
subscriptlist = 1066
subscript = 1067
sliceop = 1068
exprlist = 1069
testlist = 1070
dictmaker = 1071
classdef = 1072
arglist = 1073
argument = 1074
list_iter = 1075
list_for = 1076
list_if = 1077
gen_iter = 1078
gen_for = 1079
gen_if = 1080
testlist1 = 1081
encoding_decl = 1082
yield_expr = 1083

#--end constants--

tok_name = sym_name = {}
for _name, _value in globals().items():
    if type(_value) is type(0):
        sym_name[_value] = _name

del _name
del _value
