#  This file is automatically generated; change it on your own risk!

#--begin constants--

single_input = 831000
file_input = 831001
eval_input = 831002
decorator = 831003
decorators = 831004
funcdef = 831005
parameters = 831006
varargslist = 831007
fpdef = 831008
fplist = 831009
stmt = 831010
simple_stmt = 831011
small_stmt = 831012
expr_stmt = 831013
augassign = 831014
print_stmt = 831015
del_stmt = 831016
pass_stmt = 831017
flow_stmt = 831018
break_stmt = 831019
continue_stmt = 831020
return_stmt = 831021
yield_stmt = 831022
raise_stmt = 831023
import_stmt = 831024
import_name = 831025
import_from = 831026
import_as_name = 831027
dotted_as_name = 831028
import_as_names = 831029
dotted_as_names = 831030
dotted_name = 831031
global_stmt = 831032
exec_stmt = 831033
assert_stmt = 831034
compound_stmt = 831035
if_stmt = 831036
while_stmt = 831037
for_stmt = 831038
try_stmt = 831039
with_stmt = 831040
with_var = 831041
except_clause = 831042
suite = 831043
testlist_safe = 831044
old_test = 831045
old_lambdef = 831046
test = 831047
or_test = 831048
and_test = 831049
not_test = 831050
comparison = 831051
comp_op = 831052
expr = 831053
xor_expr = 831054
and_expr = 831055
shift_expr = 831056
arith_expr = 831057
term = 831058
factor = 831059
power = 831060
atom = 831061
listmaker = 831062
testlist_gexp = 831063
lambdef = 831064
trailer = 831065
subscriptlist = 831066
subscript = 831067
sliceop = 831068
exprlist = 831069
testlist = 831070
dictmaker = 831071
classdef = 831072
arglist = 831073
argument = 831074
list_iter = 831075
list_for = 831076
list_if = 831077
gen_iter = 831078
gen_for = 831079
gen_if = 831080
testlist1 = 831081
encoding_decl = 831082
yield_expr = 831083
as_name = 831084
repeat_stmt = 831085
switch_stmt = 831086
case_stmt = 831087
thunk_stmt = 831088

#--end constants--

tok_name = sym_name = {}
for _name, _value in globals().items():
    if type(_value) is type(0):
        sym_name[_value] = _name

del _name
del _value
