#  This file is automatically generated; change it on your own risk!

#--begin constants--

file_input = 981000
rule = 981001
rhs = 981002
alt = 981003
item = 981004
atom = 981005

#--end constants--

tok_name = sym_name = {}
for _name, _value in globals().items():
    if type(_value) is type(0):
        sym_name[_value] = _name

del _name
del _value
