#  This file is automatically generated; change it on your own risk!

#--begin constants--

eval_input = 981000
file_input = 981001
rule = 981002
rhs = 981003
alt = 981004
item = 981005
atom = 981006

#--end constants--

tok_name = sym_name = {}
for _name, _value in globals().items():
    if type(_value) is type(0):
        sym_name[_value] = _name

del _name
del _value
