#  This file is automatically generated; change it on your own risk!

#--begin constants--

ENDMARKER = 111000
NAME = 111001
NUMBER = 111002
STRING = 111003
NEWLINE = 111004
INDENT = 111005
DEDENT = 111006
LPAR = 111007
RPAR = 111008
LSQB = 111009
RSQB = 111010
COLON = 111011
PLUS = 111012
STAR = 111013
VBAR = 111014
COMMENT = 111015
token_input = 111016
unit = 111017
LBRA = 111018
RBRA = 111019
COMMA = 111020
LINE_COMMENT = 111021
WHITE = 111022
Single = 111023
Double = 111024

#--end constants--

tok_name = sym_name = {}
for _name, _value in globals().items():
    if type(_value) is type(0):
        sym_name[_value] = _name

del _name
del _value

token_map = {'""(A_BACKSLASHANY|ANY)*""': 111024,
 '"(A_BACKSLASHANY|ANY)*"': 111025,
 '#': 111022,
 '(': 111008,
 ')': 111009,
 '*': 111014,
 '+': 111013,
 ',': 111021,
 ':': 111012,
 'A_CHAR(A_CHAR|A_DIGIT)*': 111002,
 'A_DIGIT+': 111003,
 'A_LINE_END': 111005,
 'A_WHITE+': 111023,
 'LINE_COMMENTANY*A_LINE_END': 111016,
 'NAME|NEWLINE|LPAR|RPAR|LSQB|RSQB|COLON|PLUS|STAR|WHITE|VBAR|STRING|COMMENT|LBRA|RBRA|COMMA': 111018,
 'Single|Double': 111004,
 'T_DEDENT': 111007,
 'T_ENDMARKER': 111001,
 'T_INDENT': 111006,
 '[': 111010,
 ']': 111011,
 'unit*ENDMARKER': 111017,
 '{': 111019,
 '|': 111015,
 '}': 111020}
